// Language color mapping
export const getLanguageColor = (language) => {
  const colors = {
    JavaScript: "#f1e05a",
    TypeScript: "#3178c6",
    Python: "#3572A5",
    Java: "#b07219",
    Go: "#00ADD8",
    Rust: "#dea584",
    "C++": "#f34b7d",
    "C#": "#178600",
    PHP: "#4F5D95",
    Ruby: "#701516",
    Swift: "#ffac45",
    Kotlin: "#A97BFF",
    Shell: "#89e051",
    Dart: "#00B4AB",
    R: "#198CE7",
  };
  return colors[language] || "#8b949e";
};

// Heat level indicator
export const getHeatIndicator = (level) => {
  const indicators = {
    1: "🔥",
    2: "🔥🔥",
    3: "🔥🔥🔥",
  };
  return indicators[level] || "🔥";
};

// Sort repositories by different criteria
export const sortRepositories = (repos, sortBy) => {
  const sorted = [...repos];
  
  switch (sortBy) {
    case "stars":
      return sorted.sort((a, b) => b.stars - a.stars);
    case "views":
      return sorted.sort((a, b) => (b.views || 0) - (a.views || 0));
    case "growth":
      return sorted.sort((a, b) => b.starsToday - a.starsToday);
    case "discussed":
      return sorted.sort((a, b) => (b.discussions || 0) - (a.discussions || 0));
    default:
      return sorted;
  }
};

// Spoken languages list
export const SPOKEN_LANGUAGES = [
  "any",
  "abkhazian",
  "afar",
  "afrikaans",
  "akan",
  "albanian",
  "amharic",
  "arabic",
  "aragonese",
  "armenian",
  "assamese",
  "avaric",
  "avestan",
  "aymara",
  "azerbaijani",
  "bambara",
  "bashkir",
  "basque",
  "belarusian",
  "bengali",
  "bihari",
  "bislama",
  "bosnian",
  "breton",
  "bulgarian",
  "burmese",
  "catalan",
  "chamorro",
  "chechen",
  "chichewa",
  "chinese",
  "chuvash",
  "cornish",
  "corsican",
  "cree",
  "croatian",
  "czech",
  "danish",
  "divehi",
  "dutch",
  "dzongkha",
  "english",
  "esperanto",
  "estonian",
  "ewe",
  "faroese",
  "fijian",
  "finnish",
  "french",
  "fula",
  "galician",
  "georgian",
  "german",
  "greek",
  "guaraní",
  "gujarati",
  "haitian",
  "hausa",
  "hebrew",
  "herero",
  "hindi",
  "hiri motu",
  "hungarian",
  "interlingua",
  "indonesian",
  "interlingue",
  "irish",
  "igbo",
  "inupiaq",
  "ido",
  "icelandic",
  "italian",
  "inuktitut",
  "japanese",
  "javanese",
  "kalaallisut",
  "kannada",
  "kanuri",
  "kashmiri",
  "kazakh",
  "khmer",
  "kikuyu",
  "kinyarwanda",
  "kyrgyz",
  "komi",
  "kongo",
  "korean",
  "kurdish",
  "kwanyama",
  "latin",
  "luxembourgish",
  "ganda",
  "limburgish",
  "lingala",
  "lao",
  "lithuanian",
  "luba-katanga",
  "latvian",
  "manx",
  "macedonian",
  "malagasy",
  "malay",
  "malayalam",
  "maltese",
  "māori",
  "marathi",
  "marshallese",
  "mongolian",
  "nauru",
  "navajo",
  "northern ndebele",
  "nepali",
  "ndonga",
  "norwegian bokmål",
  "norwegian nynorsk",
  "norwegian",
  "nuosu",
  "southern ndebele",
  "occitan",
  "ojibwe",
  "old church slavonic",
  "oromo",
  "oriya",
  "ossetian",
  "panjabi",
  "pāli",
  "persian",
  "polish",
  "pashto",
  "portuguese",
  "quechua",
  "romansh",
  "kirundi",
  "romanian",
  "russian",
  "sanskrit",
  "sardinian",
  "sindhi",
  "northern sami",
  "samoan",
  "sango",
  "serbian",
  "scottish gaelic",
  "shona",
  "sinhala",
  "slovak",
  "slovene",
  "somali",
  "southern sotho",
  "spanish",
  "sundanese",
  "swahili",
  "swati",
  "swedish",
  "tamil",
  "telugu",
  "tajik",
  "thai",
  "tigrinya",
  "tibetan",
  "turkmen",
  "tagalog",
  "tswana",
  "tonga",
  "turkish",
  "tsonga",
  "tatar",
  "twi",
  "tahitian",
  "uyghur",
  "ukrainian",
  "urdu",
  "uzbek",
  "venda",
  "vietnamese",
  "volapük",
  "walloon",
  "welsh",
  "wolof",
  "western frisian",
  "xhosa",
  "yiddish",
  "yoruba",
  "zhuang",
  "zulu",
];

// Sort options
export const SORT_OPTIONS = [
  { value: "stars", label: "Most Starred" },
  { value: "views", label: "Most Viewed" },
  { value: "growth", label: "Fastest Growing" },
  { value: "discussed", label: "Most Discussed" },
];
